### ISSUE TITLE
files

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_opts_report#1]
Если скачать релиз- то он не раб. в 1.0.0
если скачать зип с файлами, он не имеет файл pluginst.

**Comment by kvichans** [comment]
> релиз- то он не раб.

Да, и у меня - исправляю..

Что такое "pluginst"?

**Comment by Alexey-T** [comment]
install.inf. файл. Надо класть в плаги

**Comment by kvichans** [comment]
Тут какое-то недоразумение - в [zip](https://github.com/kvichans/cuda_opts_report/releases/download/ver-1.0/plugin.OptionsReport.zip) уже есть install.inf

**Comment by Alexey-T** [comment]
В репо(репозиторий) его нет

**Comment by Alexey-T** [comment]
ошибся.
Он есть

**Comment by kvichans** [comment]
Не смог сходу понять причину
Сделал заплатку = подстроил cudax_lib
- обновите [плагин](https://github.com/kvichans/cuda_opts_report/blob/master/__init__.py)
- обновите [cudax_lib](https://github.com/kvichans/cudax_lib/blob/master/__init__.py)

**Comment by Alexey-T** [comment]
cudax-релизено. Можно толлько плаг обновить? без cudax

**Comment by kvichans** [comment]
нет

**Comment by kvichans** [comment]
либо так:
- проверьте, что с новой версией cudax нормально
- я буду дальше искать причину (мб можно будет вернуть пред.версию cudax)

**Comment by Alexey-T** [comment]
> буду дальше искать причину

плс.

**Comment by kvichans** [comment]
Разобрался. Было две ошибки. Выложил и исходник и сборку
