### ISSUE TITLE
0.9.1

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_opts_report#3]
не раб. в Куд 1.0.0

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cudatext/py/cuda_opts_report/__init__.py", line 196, in run
    if do_report(htm_file):
  File "/home/user/.cudatext/py/cuda_opts_report/__init__.py", line 72, in do_report
    def_opts    = apx._get_file_opts(def_json, {},  object_pairs_hook=collections.OrderedDict)
TypeError: _get_file_opts() got an unexpected keyword argument 'object_pairs_hook'
```

это сборка 0.9.1.

**Comment by Alexey-T** [comment]
или не эту сборку брать?

**Comment by kvichans** [comment]
Брать последний релиз "0.9.1" (он должен работать с вашим cudax)
Предыдущий был "1.0.0" - это я перепутал, поставил не тот тэг

**Comment by kvichans** [comment]
Ой! сори, только сейчас понял, что обновлять cudax нужно в любом случае

**Comment by Alexey-T** [comment]
dll hell
обновлю cudax -но потом..

**Comment by kvichans** [comment]
Берите из https://github.com/kvichans/cudax_lib/blob/master/__init__.py

**Comment by kvichans** [comment]
Да, моя вина
Буду впредь внимательнее к этому

**Comment by Alexey-T** [comment]
Почти dll hell
