### ISSUE TITLE
Too long opt value

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_opts_report#6]
`caret,C,170|enc,C,105|ends,C,50|lexer,C,140|tabsize,C,80|msg,L,`- лучше разбить на 2, изза этой оп, все разъехалось.

**Comment by Alexey-T** [comment]
Таблица2 так же
`60 colors: 3*20|142 colors: 7-hexagon|216 web-colors: 9-hexagon|3221 colors: 7-hexagon, dialog|146 named colors|420 named colors: 12*35`

**Comment by kvichans** [comment]
Что разъехалось? Снимок нужен

**Comment by Alexey-T** [comment]
Вот. Скрол не умещается гориз-й
![toolong](https://cloud.githubusercontent.com/assets/4154978/22625212/84acf420-eba9-11e6-887f-55cc22007e1b.png)

**Comment by kvichans** [comment]
Не вижу в этом проблемы
